### Import Libraries

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

### Load Dataset

In [2]:
df = pd.read_csv("cleaned_data.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1337 entries, 0 to 1336
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1337 non-null   int64
 1   sex       1337 non-null   str
 2   bmi       1337 non-null   float64
 3   children  1337 non-null   int64
 4   smoker    1337 non-null   str
 5   region    1337 non-null   str
 6   charges   1337 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 94.4 KB

In [3]:
### Divide dataset into x and y
x = df[['age', 'sex', 'bmi', 'children', 'smoker', 'region']]
y = df['charges']
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
# Creating Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
# categorical columns only
categorical_cols = ['sex', 'smoker', 'region']
# OneHotEncoder
ohe = OneHotEncoder(handle_unknown="ignore")
# ColumnTransformer
ct = ColumnTransformer(transformers=[('ohe', ohe, categorical_cols)], remainder = 'passthrough')
# Model
model = LinearRegression()
# Pipeline
pipe = make_pipeline(ct, model)
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1332   50    male  30.970         3     no  northwest  10600.54830
1333   18  female  31.920         0     no  northeast   2205.98080
1334   18  female  36.850         0     no  southeast   1629.83350
1335   21  female  25.800         0     no  southwest   2007.94500
1336   61  female  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [5]:
# Divide into train and test, train and calculate accuracy
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
scores = []
for i in range(0, 101):
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = i)
    pipe.fit(x_train, y_train)
    y_pred = pipe.predict(x_test)
    y_pred = pd.DataFrame(data = y_pred, columns =['Prediction'])
    result = pd.concat([y_test.reset_index(drop = True), y_pred.reset_index(drop = True)], axis = 1)
    score = r2_score(result["charges"], result["Prediction"])
    scores.append(score)
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1332   50    male  30.970         3     no  northwest  10600.54830
1333   18  female  31.920         0     no  northeast   2205.98080
1334   18  female  36.850         0     no  southeast   1629.83350
1335   21  female  25.800         0     no  southwest   2007.94500
1336   61  female  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [6]:
# Get index of max value
index = np.argmax(scores)
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1332   50    male  30.970         3     no  northwest  10600.54830
1333   18  female  31.920         0     no  northeast   2205.98080
1334   18  female  36.850         0     no  southeast   1629.83350
1335   21  female  25.800         0     no  southwest   2007.94500
1336   61  female  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [7]:
# Let split using best index and train
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = index)
pipe.fit(x_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['sex', 'smoker',
                                                   'region'])])),
                ('linearregression', LinearRegression())])

In [8]:
# Check for user input

myinput = [[ 25,  # age
             
'male', # sex

28.5,  # bmi

2,  # children

'no',  # smoker

'southwest' # region
]]
columns = ['age', 'sex', 'bmi', 'children', 'smoker', 'region']

myinput = pd.DataFrame(data=myinput, columns=columns)

result = pipe.predict(myinput)

print("Predicted Hospital Treatment Cost is:", round (result[0]))

Predicted Hospital Treatment Cost is: 4043

In [9]:
# Export pipe(model) using pickle
import pickle
pickle.dump(pipe,
open("hospital_pipe.pkl", "wb"))